version: '3'
services:

  react:
    build:
      dockerfile: ./frontEnd/Dockerfile
      context: .
    container_name: react
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/scr/app

  node:
    build:
      dockerfile: ./backEnd/Dockerfile
      context: .
    container_name: node
    ports:
      - "3030:3030"
    volumes:
      - ./:/usr/scr/app
    networks:
      - library
    depends_on:
      - mysql-db

  mysql-phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminLibrary
    ports:
      - 8080:80
    networks:
      - library
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  mysql-db:
    image: mysql:5.7
    container_name: mysqlLibrary
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - library
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products

networks:
  library:
    driver: bridge

volumes:
  mysql:
